# -*- coding: utf-8 -*-
# Copyright 2015, 2016, 2017 Ravshello Authors
# License: Apache License 2.0 (see LICENSE or http://apache.org/licenses/LICENSE-2.0.html)

# All references to program name should use this
prog = 'ravshello'

# Version info
__version__ = '1.35.0'
__date__ = '2017/09/26'
version = "{} v{} last mod {}".format(prog, __version__, __date__)

# Defaults
defaultUserCfgDir = '~/.ravshello'
defaultUserCfgFile = 'config.yaml'
defaultAppExpireTime = 120
defaultAppExtendTime = 60

# Some learner mode rules
maxLearnerPublishedApps = 3
maxLearnerActiveVms = 8
maxLearnerExtendTime = 120

# Learner mode can only create apps from blueprints which have
# one of these strings in their description
learnerBlueprintTag = [
    "#is_learner_blueprint",
    "#learner_bp",
]

# Both learner and admin will only be able to publish blueprints that have a
# bmc tag to a bmc region; blueprints lacking a bmc tag will not be publishable
# in bmc regions
bmcBlueprintTag = [
    "#is_bmc_blueprint",
    "#bmc",
]

# List of BMC (bare-metal-cloud) regionNames
bmcRegionNames = ['us-east-5', 'us-southwest-1', 'eu-central-3', 'eu-west-5']

amazonBlueprintTag = ['#amazon']
amazonRegionNames = [
    'us-west-1', 'us-west-2', 'us-east-3', 'us-east-1', 'ap-northeast-2',
    'ap-south-1', 'eu-central-1', 'eu-west-1', 'eu-west-3', 'ap-northeast-1',
    'ca-central-1', 'sa-east-1', 'ap-southeast-2', 'ap-southeast-1'
]

googleBlueprintTag = ['#google']
googleRegionNames = [
    'europe-west-6', 'mumbai-2', 'us-central-1', 'us-east-4', 'eu-west-4',
    'ap-southeast-3', 'ap-southeast-4', 'eu-central-2', 'us-east-6',
    'sa-east-2', 'us-west-3', 'ap-northeast-3', 'eu-west-2', 'ap-east-1'
]

oracleBlueprintTag = ['#oracle']
oracleRegionNames = ['us-east-5', 'us-southwest-1', 'eu-central-3', 'eu-west-5']

regionCatalog = {
    "#is_bmc_blueprint": bmcRegionNames,
    "#bmc": bmcRegionNames,
    "#amazon": amazonRegionNames,
    "#google": googleRegionNames,
    "#oracle": oracleRegionNames
}
# This will hold the options namespace generated by argparse
opts = None

# This will hold the "local" username (nickname)
user = None

# This holds the string that builds app name prefix w/nickname (see config.yaml)
appnameNickPrefix = 'k:'

# This will hold the default app cost bucket (see config.yaml)
appCostBucket = None

# This will hold the RavelloClient object
rClient = None

# This will hold the RavelloCache object
rCache = None

# This will hold the options read from config files
cfgFile = {}
